### ISSUE TITLE
Allow configuring keyboard shortcut

### ISSUE THREAD

**Issue by majutsushi** [jlebon/textern#1]
Hi,

Thanks for creating this very useful extension, now that ItsAllText is sadly going away. There's only one big issue, at least for me: the default keyboard shortcut clashes with other shortcuts I use, in this case with the Emacs Ctrl-E standard keybinding (which is enabled at the global GTK level), which means that it doesn't get passed through to the extension, making it impossible to use. The only way I could find to change that was to modify the extension code and install that, which was quite an effort with the mandatory signing in place now. So it would be great if the shortcut could instead be configurable. Thanks!

**Comment by jlebon** [comment]
Thanks for using it!

Yeah, that's definitely a natural feature to have.

**Comment by lilydjwg** [comment]
<kbd>Ctrl+Shift+E</kbd> for whatever reason doesn't work for me (nightly). Hope this can be fixed soon so I can move more work to nightly from esr.

**Comment by wavexx** [comment]
It seems that on GTK3, `Ctrl+Shift+E` (as most vowels) are bound for hex unicode input[!]. Even by manually disabling this, ctrl+[shift+]anything doesn't seem to work in a textarea. At all.

It only works when the page is selected, making it useless for this extension.
I manually changed the shortcut to F2, which seems to work.

**Comment by jlebon** [comment]
`Ctrl-Shift+E` also no longer works for me in FF55. Will take a look at it soon.

> It seems that on GTK3, Ctrl+Shift+E (as most vowels) are bound for hex unicode input[!].

It's odd, that wasn't an issue for me before, but I do hit it as well now.

**Comment by wavexx** [comment]
On Thu, Sep 14 2017, Jonathan Lebon wrote:
>     It seems that on GTK3, Ctrl+Shift+E (as most vowels) are bound for hex unicode input
>     [!].
>
> It's odd, that wasn't an issue for me before, but I do hit it as well now.

Must be something recent, as I also had the same key bound in
withExEditor (legacy version), and that stopped working as well.

**Comment by jlebon** [comment]
This is fixed in the latest version of Textern (v0.4), though it is still under review. In the meantime, you can download the XPI directly [here](https://addons.mozilla.org/firefox/downloads/file/734874/textern-0.4-an+fx-linux.xpi). I left the default shortcut as `Ctrl+Shift+E` (which should work again).

Feel free to re-open if you encounter any issues! :)

**Comment by wavexx** [comment]
It works, in a weird way.

Ctrl+Shift+e seem to actually insert the letter into the textarea, but then it's removed and the external editor is run. As a side effect of this though, the textarea scrolling position is moved to the bottom.

The same doesn't happen with F2 (for example).
Is this a work-around you found somehow?

**Comment by jlebon** [comment]
Yeah, that happens to me too, though I hadn't noticed since the textarea is almost always in the view already. But at least it's easily configurable now! Will see, might change the default to something else.

**Comment by majutsushi** [comment]
I set the shortcut to <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>i</kbd>, and everything seems to be working as expected. Thanks!
