### ISSUE TITLE
Support Program Arguments

### ISSUE THREAD

**Issue by naclander** [jlebon/textern#11]
If I wanted to use emacsclient to open and edit the file, I need to invoke it via `emacsclient -c $FILENAME`.
However, `emacsclient -c` doesn't seem to be a valid external editor command to textern. It would be great if I could do this.

P.S. thanks for the great addon.

**Comment by jlebon** [comment]
The filename is automatically appended to the list of arguments. So e.g. `["emacsclient", "-c"]` will actually invoke `emacsclient -c /path/to/file.txt`. If you'd like the filename argument to not be last, you can use `%s`, e.g. `["emacsclient", "-c", "%s", "--other-option"]`.

> P.S. thanks for the great addon.

Glad you like it! :)

**Comment by naclander** [comment]
Oh great, that's exactly what I wanted.

I remember seeing this mentioned in the README, but I think I misunderstood
that the extra strings in the list are arguments to the first element. Maybe an additional example would be useful.

Anyway, this does what I want, so I'll go ahead and close this issue.

**Comment by jlebon** [comment]
Thanks! I amended the README to make it clearer how argument passing works: https://github.com/jlebon/textern/commit/be6135d12c8ac862130e4f27e1a8d0f89a478744.
