### ISSUE TITLE
no effect, or: this text is already being edited

### ISSUE THREAD

**Issue by hurdsean** [jlebon/textern#14]
I followed the instructions ([install.txt](https://github.com/jlebon/textern/files/1496264/install.txt))

To test I changed the preferences for External editor to:  ["sh", "-c", "echo foobar > $0"]
and Shortcut to: Alt+o

When I open a textarea field, click in it, and hit alt+o, nothing happens. When I hit alt+o again, I get an error pop-up (from X or the window manager?) which says: this text is already being edited. I also tried the default Ctrl+Shift+E as trigger. The error has an "activate" button, but nothing happens when I click that. 

![error](https://user-images.githubusercontent.com/5187760/33133514-568f44d4-cf9d-11e7-9bb3-fe65c7e7a6ba.png)

The same happens when I choose for External editor: ["gvim", "-f"] or  ["gvim"]. 

My system is Slackware 14.2, Openbox  3.6.1, and I tried Firefox Developer Edition 58.0b5 (64-bit) and Firefox 57 (64-bit). I'v got both Python 2.7.11 and Python 3.6.2 (according to Slackbuilds they can live together, I run one other program with Python 3, https://github.com/leoboiko/myougiden.git).

**Comment by jlebon** [comment]
> To test I changed the preferences for External editor to: ["sh", "-c", "echo foobar > $0"]
and Shortcut to: Alt+o

Do you see any errors in the browser console? (Ctrl+Shift+J) Is textern still running in the background after the first press?

Re. that "Activate" button, interesting, I'm not sure where that comes from. Textern uses the basic Firefox notification API, which on Linux at least uses libnotify. Could be an issue with whatever notification daemon Openbox uses.

**Comment by hurdsean** [comment]
> Do you see any errors in the browser console? (Ctrl+Shift+J) 

 `No such native application textern`  
`▷ this.NativeApp</this.startupPromise<`

Second press:  
`Error: document id 1_0 is already being edited`

![2017-11-23_1734x45_001___1st_press](https://user-images.githubusercontent.com/5187760/33165910-b9f9d9c6-d038-11e7-9be8-bcfd5ed0ad1e.png)
![2017-11-23_1692x20_002___2nd_press](https://user-images.githubusercontent.com/5187760/33165938-c14a14fc-d038-11e7-8b4a-7214b9d4119b.png)

> Is textern still running in the background after the first press?  

I can't find textern with ps aux

**Comment by jlebon** [comment]
Ahh OK. This means that Firefox couldn't find the manifest file. I see in the installation logs that you installed it system-wide. Did you build and install Firefox with a non-`/usr` prefix by any chance? You can override `MOZILLA_PREFIX` as needed if so.

Alternatively, try uninstalling it system-wide (`sudo make native-uninstall`) and reinstalling it for just yourself (`make native-install USER=1`).

**Comment by hurdsean** [comment]
Oh. Somewhat embarrassing that I failed to consider and mention that I run Firefox from `~/bin`. 

Uninstalling and installing with `make native-install USER=1` seems to have fixed the problem. For gvim users: I used `["gvim", "-f"]`. 

Thanks for your time and patience.  

Can I mention a feature request? Just ignore if that's rude. Here it is: would be cool if you'd allow access to `<input type="text">` fields  as well. Examples of usage: edit forms fields that are too small; use one's editor as a more capable IME for special characters that can't be typed (easily) into Firefox otherwise. 

Thanks again.

**Comment by jlebon** [comment]
Sweet, happy to hear it's working now! I'm going to close this issue then.

> would be cool if you'd allow access to `<input type="text">` fields as well.

Sure, that sounds reasonable. I opened [a new issue](https://github.com/jlebon/textern/issues/15) to track that.
