### ISSUE TITLE
No way to pass arguments to the external editor

### ISSUE THREAD

**Issue by majutsushi** [jlebon/textern#2]
It would be useful if there were a way to pass specific arguments to the external editor. In my case I want to use GVim, which forks into the background unless the `-f` argument is used, similarly to the gnome-terminal issue mentioned in the README. Specifying the editor as `gvim -f` doesn't work because the whole string gets interpreted as the editor name. Of course it's possible to write a short wrapper script for this, but it would be nice if it weren't necessary.

**Comment by jlebon** [comment]
The setting allows you to pass the command in the JSON/YAML list format, specifically to avoid quoting issues. E.g. this should work:

```json
["gvim", "-f"]
```

**Comment by jlebon** [comment]
(The tooltip for the textbox gives the format expected, though I suppose I should make that more discoverable.)

**Comment by majutsushi** [comment]
You're right, I totally missed that. I just tried it and it works great. I actually saw that you can have multiple elements there, but for some reason I thought it was for specifying alternatives instead of arguments. No idea how I came up with that idea.
