### ISSUE TITLE
Pass the line/column to the editor

### ISSUE THREAD

**Issue by phdru** [jlebon/textern#22]
Does Mozilla pass the line/column to the extension? Or may be there is a way to interrogate Mozilla for this additional information?

IWBN to pass them to the editor via command line. Something like `["gvim", "-f",  "+$l", "-c", "normal $c|" $f]` where `$l`, `$c` and `$f` are placeholders for line, column and file name.

Any syntax will do: `%l`, `%c` and `%f`, e.g.

**Comment by jlebon** [comment]
This feature was added in version v0.5. I've just submitted it to AMO!

**Comment by phdru** [comment]
Excellent! Thank you!
