### ISSUE TITLE
IBUS ctrl-shift-e brings up 'emoji' menu and not textern

### ISSUE THREAD

**Issue by rich-coe** [jlebon/textern#25]
Firefox version 58 update installed~~ JIRA comment box~~ and now when I type ctrl-shift-e in a text box, I get a stupid emoji menu.  I haven't found a way to turn off the emoji junk and get textern back.

**Comment by rich-coe** [comment]
I use this feature with JIRA but noticed it after a Firefox upgrade.  I then thought it wasn't FF specific, but only JIRA, but I see the emoji screen starting on other text boxes too, not just JIRA.

**Comment by rich-coe** [comment]
Found it's an IBUS option.   Open the IBUS Preferences, select the 'EMOJI' tab, and change the configuration.

**Comment by rich-coe** [comment]
re-mapping the char doesn't work yet.

**Comment by rich-coe** [comment]
I turned off the mapping of ctrl-shift-e in IBUS.  I restarted both IBUS and firefox.  ctrl-shift-e still is not working in a text box in FF.

**Comment by jlebon** [comment]
Hmm, works on FF58 here at least. :)
Have you tried just changing the Textern hotkey to something else?

**Comment by rich-coe** [comment]
It works with some text boxes, so I'm back to where it was before.
