### ISSUE TITLE
shortcut does not start editor

### ISSUE THREAD

**Issue by ruudgrosmann** [jlebon/textern#28]
I have installed textern in a fresh ubuntu aardvark install (ff 5.8).
I have changed the editor to gvim, which is installed.
PRessing CS-E has no effect, only a e is shown in the textbox where I press it.
Python 3.6 is installed and after some googling I have installed python-pyinotify too.

What can I do to get this addon working?

Ruud

**Comment by ruudgrosmann** [comment]
I found out that when I change the shortcut key to control shift I, textern _is_ invoked (although it gives an error). That indicates this default shortcut is being overruled by firefox itself.  Maybe it is good to communicate this somehow with the user.

**Comment by ruudgrosmann** [comment]
When I restart ff and I invoke textern by pressing the shortcut key, the error console says
```
Object { shiftKey: true, metaKey: false, altKey: false, ctrlKey: true, repeat: false, key: "I", bubbles: true, composed: true, defaultPrevented: false, eventPhase: 1, 4 more… } insert  background.js:1308:17
Array [ "I" ] Object { keys: Array[0], ex_str: undefined }  background.js:1326:17
context.runSafeWithoutClone called while context is inactive ExtensionCommon.jsm:280
No such native application textern  NativeMessaging.jsm:100
```
Nothing happens. When I hit again the shortcutkey the message is now
```
Object { shiftKey: true, metaKey: false, altKey: false, ctrlKey: true, repeat: false, key: "I", bubbles: true, composed: true, defaultPrevented: false, eventPhase: 1, 4 more… } insert  background.js:1308:17
Array [ "I" ] Object { keys: Array[0], ex_str: undefined }  background.js:1326:17
Error: document id 1_0 is already being edited  background.js:84:9
```
In addition, a notify box is showed with the text 'document is already being edited' and from now til a ff restart, textern keeps doing this.
I found a similar question, but the difference is I have installed ff via the package installer and textern by installing it via the firefox addon menu's.

What can I do to get textern working? Or can I supply more information in order to find out what is happening?

**Comment by jlebon** [comment]
Hmm, this:

> No such native application textern

makes it seem like the native app might not be installed correctly. Can you make sure you followed the steps exactly from the README?

> after some googling I have installed python-pyinotify too

You shouldn't have to do this. Textern comes with its own bundled copy of the library.

**Comment by ruudgrosmann** [comment]
I have installed it using the firefox addon interface. Does the readme imply this is not enough and I have to build the native application just the same? Is this possible via firefox too or do I really have to pull and build?

**Comment by jlebon** [comment]
Correct, you need to install both the Firefox extension *and* the native application. They're not the same thing. The Firefox extension talks to the native application, which handles launching and monitoring the editor. This is needed because the WebExtensions API does not allow addons to directly spawn processes.

**Comment by ruudgrosmann** [comment]
OK. I installed the native application and to be safe, restarted FF. But still nothing happens, although the error console now comes up with another reaction:
```
State changed! mode normal  background.js:209:9
context.runSafeWithoutClone called while context is inactive ExtensionCommon.jsm:280
Tridactyl content script loaded, boss!  content.js:2641
Loaded initial state: <unavailable>  content.js:193
INIT  content.js:1713
Loaded initial state: <unavailable>  commandline_frame.js:193
TypeError: can't convert undefined to object  content.js:496:35
Error: Could not establish connection. Receiving end does not exist. undefined
Message: Object { type: "keydown_background", command: "recvEvent", args: Array[1] }  background.js:83:9
State changed! mode insert  background.js:209:9
Object { shiftKey: false, metaKey: false, altKey: false, ctrlKey: true, repeat: false, key: "Control", bubbles: true, composed: true, defaultPrevented: false, eventPhase: 1, 4 more… } insert  background.js:1308:17
Array [ "Control" ] Object { keys: Array[0], ex_str: undefined }  background.js:1326:17
context.runSafeWithoutClone called while context is inactive ExtensionCommon.jsm:280
Message: Object { type: "keydown_background", command: "recvEvent", args: Array[1] }  background.js:83:9
State changed! mode insert  background.js:209:9
Object { shiftKey: true, metaKey: false, altKey: false, ctrlKey: true, repeat: false, key: "Shift", bubbles: true, composed: true, defaultPrevented: false, eventPhase: 1, 4 more… } insert  background.js:1308:17
Array [ "Shift" ] Object { keys: Array[0], ex_str: undefined }  background.js:1326:17
context.runSafeWithoutClone called while context is inactive ExtensionCommon.jsm:280
Message: Object { type: "keydown_background", command: "recvEvent", args: Array[1] }  background.js:83:9
State changed! mode insert  background.js:209:9
Object { shiftKey: true, metaKey: false, altKey: false, ctrlKey: true, repeat: false, key: "I", bubbles: true, composed: true, defaultPrevented: false, eventPhase: 1, 4 more… } insert  background.js:1308:17
Array [ "I" ] Object { keys: Array[0], ex_str: undefined }  background.js:1326:17
Error: document id 7_0 is already being edited  background.js:84:9
context.runSafeWithoutClone called while context is inactive ExtensionCommon.jsm:280
```

Maybe you can see from this what is misconfigured? Thanks for helping, Ruud

**Comment by jlebon** [comment]
Hmm, I'm not seeing anything obvious, though I see you have Tridactyl installed. Can you try with the addon disabled to make sure we can rule it out?

**Comment by ruudgrosmann** [comment]
I have disabled tridactyl, but there are still problems.
The first time I tried invoking textern bij using the shortcut key I got
```
TypeError: Argument 1 of PrecompiledScript.executeInGlobal is not an object.[Learn More]  ExtensionContent.jsm:357:18
uncaught exception: undefined  (unknown)
GET
TypeError: Argument 1 of PrecompiledScript.executeInGlobal is not an object.[Learn More]  ExtensionContent.jsm:357:18
uncaught exception: undefined  (unknown)
GET
http://10.12.25.140/twiki/cgi-bin/edit/Ruud/PagScala
[HTTP/1.1 401 Unauthorized 2ms]
TelemetryStopwatch: key "FX_SCHEDULE_PRESSURE_IDLE_SAMPLE_MS" was already initialized  TelemetryStopwatch.jsm:356
[Exception... "Component is not available"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://gre/modules/WebRequest.jsm :: applyChanges :: line 786"  data: no]  (unknown)
Key event not available on some keyboard layouts: key=“r” modifiers=“accel,alt” id=“key_toggleReaderMode”  browser.xul
Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” id=“key_browserToolbox”  browser.xul
No such native application textern
```

after restarting ff and retrying, this changed to
```
Error: Could not establish connection. Receiving end does not exist. undefined
Error: document id 6_0 is already being edited  background.js:84:9
Error: WebExtension context not found!  ExtensionParent.jsm:830:13
Error: Could not establish connection. Receiving end does not exist. undefined
```
pressing the shortcut key combination once again resulted in the document being edited notify and in the error console
`Error: document id 6_0 is already being edited`

I am afraid this only makes it more difficult to trace down what is going on... :(

Ruud

**Comment by jlebon** [comment]
> No such native application textern

Ahh, this is a sign that the native app wasn't installed properly. Did you install with `sudo make native-install`? If so, can you try:

```
sudo make native-uninstall
make native-install USER=1
```

**Comment by jlebon** [comment]
Some folks have been having issues with the default privileged native install. The unprivileged location seems to have worked for them.

**Comment by ruudgrosmann** [comment]
hi Jonathan,
I have followed your instructions and it is definitely an improvement. I had to restart firefox in order to see the effect of the native installation though.
After that this happens: when I press the shortcut key combination in a text box, gvim starts up, but with an empty contents (the textbox contains a LOT of text). When I change this by adding some text and saving and quitting (ZZ), I get an error message stating the tmp-file cannot be written:
```
<40%2Ftwiki%2Fcgi-bin%2Fedit%2FRuud%2FPagSbt-_9flrkv0.txt [+] 1 1 100%
<-lt8j56pa/10.12.25.140%2Ftwiki%2Fcgi-bin%2Fedit%2FRuud%2FPagSbt-_9flrkv0.txt"
"/tmp/textern-lt8j56pa/10.12.25.140%2Ftwiki%2Fcgi-bin%2Fedit%2FRuud%2FPagSbt-_9f
lrkv0.txt" E212: Can't open file for writing    
```  
It appears the directory is non existent. When I create it while the editor is still open and save again, gvim  quits, but the textbox is not changed accordingly (I expected the lots of text be replaced by the new contents).
Retrying this comes up with the same problem, now with another non existing tmp directory.

```
% ls -ld /tmp                                                 
drwxrwxrwt 20 root root 4096 Mar  7 09:18 /tmp/
% ls -ld /tmp/textern-lt8j56pa                                
drwxrwxr-x 2 rdgon rdgon 4096 Mar  7 09:17 /tmp/textern-lt8j56pa/
```


I hope this gives some clue what could be wrong now. 

Ruud

**Comment by jlebon** [comment]
Hmm, this might be the native app mishandling long URLs. Does it work on other websites, e.g. in this GitHub textbox?

**Comment by ruudgrosmann** [comment]
No, that is not the case. For example, this text box results in
```
"/tmp/textern-r_5qky53/github.com%2Fjlebon%2Ftextern%2Fissues%2F28-60stwzhh.txt"
 E212: Can't open file for writing 
```
I will not be able to do additional checks until monday. If there is anything I can right now do to provide additiol information, pleaset let me know.

**Comment by jlebon** [comment]
Can you share your exact config? Make sure you're passing `-f` (e.g. `["gvim", "-f"]`) like in the README.md.

**Comment by ruudgrosmann** [comment]
hi Jonathan,
the -f option was the missing link. After supplying that, everything works now. I want to thank you for your patient help. Without that I would not have made it up to this point.

best, Ruud

**Comment by jlebon** [comment]
Great, happy to hear it worked! :)
