### ISSUE TITLE
Textern may want to change the default Ctrl+Shift+E keybinding due to a Firefox and GTK3 change

### ISSUE THREAD

**Issue by siebenmann** [jlebon/textern#30]
The short version is [Firefox bug 1451818](https://bugzilla.mozilla.org/show_bug.cgi?id=1451818).

The long version: sufficiently modern versions of GTK+ 3 use Ctrl+Shift+E in text entry widgets to let you enter emoji, as documented [here](https://developer.gnome.org/gtk3/stable/GtkIMContextSimple.html). On systems with a recent enough GTK+ 3, the latest versions of Firefox have changed the generated keycode and key for Ctrl+Shift+E from the usual value of 69 and 'E' to 229 and 'Process', which is apparently the standard behavior in other browsers and also what Firefox's code may call for.

Textern could perhaps sort of cope with this by changing what keycode it's looking for to recognize this too, but that would require changes to shortcuts.js to recognize this and also block using Ctrl+Shift+E to enter emoji. I'd suggest switching to Ctrl+Alt+E, which seems to work reliably for me and which doesn't conflict with anything that I can see.

**Comment by jlebon** [comment]
Thanks for filing this! I've heard others hit it as well, though your detailed report has finally convinced me to do this.

> I'd suggest switching to Ctrl+Alt+E, which seems to work reliably for me and which doesn't conflict with anything that I can see.

This is of course subjective, though I went with `Ctrl+Shift+D`. I find `Ctrl+Alt` combinations less natural to type than `Ctrl+Shift` (though that's probably because I'm not an Emacs user :)).
