### ISSUE TITLE
Error: this text is already being edited, but editor doesn't start

### ISSUE THREAD

**Issue by valdisvi** [jlebon/textern#31]
Tested on Ubuntu with gedit, and Lubuntu with leafpad and gvim. When hot key is pressed, notification appears:
```
Textextern
Error: this text is already being edited
```
but editor is actually not opened (and there are no any running process).

**Comment by jlebon** [comment]
Can you check the browser console for error messages? Try from a freshly restarted Firefox instance.

**Comment by valdisvi** [comment]
Browser console is clear. 
System message happens, when in content.js, registerText() browser.runtime.sendMessage(...) is called.

**Comment by jlebon** [comment]
What editor are you using? Does it work with `["gedit"]`?

**Comment by valdisvi** [comment]
The same message.

**Comment by valdisvi** [comment]
How can I test textern native binaries directly without involving browser?
E.g. what should happen when I run:
```
/usr/local/libexec/textern/textern.py
```

**Comment by jlebon** [comment]
The script expects to be talking to Firefox, so it won't do anything if you just run it directly.

Some things to try:

- change the shortcut to something else -- the default combination may be getting intercepted by another program
- if you're installing using `sudo make native-install`, try instead `make native-install USER=1`
- make sure you have the latest version of Firefox; the first FF57 spin had some issues IIRC
- make sure you're checking the browser console for errors (Ctrl+Shift+J), not the developer console
- make sure you cloned the repo with `--recurse-submodules` (see https://github.com/jlebon/textern#installation)

If all the above fail, can you check after it gives the message whether Textern is still running in the background (e.g. `ps aux | grep textern`)?

**Comment by valdisvi** [comment]
Thanks!
Reinstalling with `make native-install USER=1` made it working.

**Comment by zeorin** [comment]
I had this same problem with terminal Emulator Kitty and Neovim. The posted solution worked for me, too.
