### ISSUE TITLE
Mention tridactyl as a more vim-inmersive experience

### ISSUE THREAD

**Issue by rodrigoaguilera** [jlebon/textern#32]
I have been using this extension for some time but recently I discovered that tridactyl includes the textern main feature through the ```:editor``` command.

I really liked the change.

Maybe is worth mentioning this alternative in the readme.

Thank you for such a cool extension.

**Comment by jlebon** [comment]
Just tried this out, neat!
Thanks for bringing this up, I added a mention to the README.
