### ISSUE TITLE
Textern Not Working For Gmail 

### ISSUE THREAD

**Issue by anhnamtran** [jlebon/textern#37]
### Issue:
Textern not opening an editor in text boxes in Gmail. This includes the
`Compose` and `Reply` boxes.

### Reproduction:
1. Go to Gmail.
2. Open "Compose" or "Reply" box.
3. Select text field.
4. Use shortcut.

### Things I've Tried
- Reloading Firefox.
- Changing the shortcut to `Ctrl+Shift+E`, `Ctrl+Shfit+D`, `Ctrl+Shift+I`.
  Currently using `Alt+Shift+D`.
- Tried invoking Textern on these websites: Reddit (OK), Github (OK), Facebook
  (Not OK).

### System information:
- Firefox Quantum 61.0.1 (64-bit) for Ubuntu with Vimium installed.
  - Vimium is disabled in Gmail. 
  - Vimium is _not_ disabled for Github.
- Ubuntu 18.04 LTS
- GVim using Vim version 8.1

**Comment by towo** [comment]
For what it's worth, I though that it's vimium at first, but vimium does in no way seem to affect the usage of textern.

What does not work is using it on things that are not text areas - you can only edit those, not things like search areas. Try the one to write comments here.

**Comment by jlebon** [comment]
Right, Textern currently only works on textareas. GMail uses contenteditable divs. I have a patch locally to make it work there as well, though it only works in reply boxes right now. (In the new email case, the div is created dynamically which doesn't jive with how Textern listens for hotkeys). Will try to at least polish up the working parts soon and push it out.

**Comment by anhnamtran** [comment]
Hi there, just wanted to know if there's an update on this? Thanks!

**Comment by jlebon** [comment]
@anhnamtran Hi, I posted a WIP in #43. Could you try it out and let me know if this helps?

**Comment by jlebon** [comment]
This is fixed in the v0.6 release!
