### ISSUE TITLE
Wrong permissions, editor not starting

### ISSUE THREAD

**Issue by ingo-h** [jlebon/textern#38]
I installed textern following the Installation instructions. But the editor (gvim) does not open when I hit `Ctrl+Shift+D`. After looking what's going wrong I realized that native files have no global read permission. This is because I do not use the default `umask 022` on  my system for reasons. Instead I use `umask 007`. That means new created directories and files have the permission `rw-rw----` on my system.

I have tried to correct (I would not like to set absolute permissions e.g. chmod 644): 

    sudo find /usr/lib64 -type d -exec chmod o+rx {} \;
    sudo chmod o+r /usr/lib64/mozilla/native-messaging-hosts/textern.json
    sudo find /usr/local/libexec -type d -exec chmod o+rx {} \;
    sudo find /usr/local/libexec -type f -exec chmod o+r {} \;
    sudo chmod o+x /usr/local/libexec/textern/textern.py

But this is not enough. If I install textern for the current user then everything is working.

What is to do to run textern system wide in this case?

**Comment by jlebon** [comment]
It's hard to say to be honest. I run with the default `umask` here so haven't hit this. Is it Firefox complaining it can't start the native app or is it the native app complaining it can't e.g. read the tmpfile?

**Comment by ingo-h** [comment]
In the browser console I get:

    No such native application textern  NativeMessaging.jsm:99
	    NativeApp</this.startupPromise< resource://gre/modules/NativeMessaging.jsm:99:9

**Comment by jlebon** [comment]
OK, right, that indeed sounds like it can't find/execute Textern. To confirm, is Firefox installed under `/usr`? Or `/usr/local` or e.g. `~/bin`?

**Comment by ingo-h** [comment]
~$ which firefox
    /usr/bin/firefox
    ~$ lsb_release -d
    Description:    Debian GNU/Linux 9.5 (stretch)

Firefox is installed from the default repositories.

**Comment by ingo-h** [comment]
Just for testing I have started firefox as root but get the same error message in the browser console.

**Comment by ingo-h** [comment]
I have found what's wrong. Seems firefox on Debian only looks at  
`/usr/lib/mozilla/native-messaging-hosts/textern.json`  
for the native messaging manifest and does not know  
`/usr/lib64/mozilla/native-messaging-hosts/textern.json`  
the installation is made. Reference: [Manifest location](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests#Manifest_location#Linux). I will made a pull request.
