### ISSUE TITLE
Nothing happens when I press ctrl+shift+e

### ISSUE THREAD

**Issue by olmokramer** [jlebon/textern#4]
I have installed the native part with `make native-install USER=1` and changed the editor in the plugin preferences to `["st", "vim"]` (`st` is my terminal emulator). But when I focus a textarea and press <kbd>ctrl+shift+e</kbd> nothing seems to happen except that an `e` is printed in the textarea. Do I need to install other dependencies? (saw none mentioned in the readme) Or how would I go about debugging this? Have never worked with FF plugins before...
Thanks!

**Comment by jlebon** [comment]
Are you on FF55? I've been noticing issues as well (see also #1). The browser console might have some helpful messages as well.

**Comment by jlebon** [comment]
Can you try the latest version? You can either use it from source or try the one currently under review [here](https://addons.mozilla.org/firefox/downloads/file/734874/textern-0.4-an+fx-linux.xpi). Error messages could appear in either the page console (F12) or the browser console (Ctrl+Shift+J).

**Comment by olmokramer** [comment]
I'm sorry it took so long to respond, I've stopped using Firefox and kinda forgot about this... I had been using the Firefox nightly, v57 I think it was. I've tested again, now on Firefox v58 but it still doesn't work. When I focus a textarea and press Ctrl-Shift-e an `e` appears in the textarea and nothing else. I do get a message in the Ctrl-Shift-j console: "Error: document id 2_0 is already being edited" and a notification saying "Textern: this text is already being edited".

I'm using these settings:
External editor: ["st", "-e", "nvim"]
Shortcut: Ctrl+Shift+E
Document extension: txt

**Comment by jlebon** [comment]
Hmm interesting. Can you have a look at the troubleshooting steps in https://github.com/jlebon/textern/issues/7? E.g. can you sanity check with `["sh", "-c", "echo foobar > $0"]`, which should always work? And also check whether your terminal is blocking or non-blocking to determine whether you need the wrapper script.

>"Error: document id 2_0 is already being edited" and a notification saying "Textern: this text is already being edited".

Hmm, interesting. Does this happen on the *first* press after a fresh Firefox restart? Do you see the `textern` process running?

**Comment by olmokramer** [comment]
> Hmm interesting. Can you have a look at the troubleshooting steps in #7? 

I've tried the steps from #7 but still couldn't get it to work.

> E.g. can you sanity check with `["sh", "-c", "echo foobar > $0"]`, which should always work? 

It does nothing (it should replace the text in the textarea with "foobar" right?) 

> And also check whether your terminal is blocking or non-blocking to determine whether you need the wrapper script.

My terminal is blocking, so I shouldn't need the wrapper script. 

> Hmm, interesting. Does this happen on the first press after a fresh Firefox restart? Do you see the textern process running?

I get the notification on the second press, but was under the impression it was the first because it also happened after a page reload. There's no `textern` process running at all after (or before) pressing <kbd>Ctrl+Shift+e</kbd>

**Comment by jlebon** [comment]
> > E.g. can you sanity check with ["sh", "-c", "echo foobar > $0"], which should always work?
>
> It does nothing (it should replace the text in the textarea with "foobar" right?)

Yeah, it should. Hmm OK, there is something fundamentally wrong with the setup then. Are you running the latest native app from git master? Do you have Python v3.5 at least? Are there any other errors in the browser console?

**Comment by olmokramer** [comment]
Oh silly me, I see an error message now that I hadn't seen before (it probably was there, just didn't notice...) that it couldn't find the `simple_inotify` python module. Installed it and now everything works like a charm! I couldn't find it in the readme, though, so maybe you should add it there. Thanks!

**Comment by jlebon** [comment]
Awesome, glad to hear it works! You shouldn't actually have to install `simple_inotify` yourself. It is bundled with the repo as a submodule. It sounds like the repo maybe wasn't cloned with `--recurse-submodules`?

**Comment by olmokramer** [comment]
Ah ok, yes I forgot that. I just quickly installed the plugin again without carefully reading the installation instructions. After uninstalling `simple_inotify` and pulling in the submodules everything still works fine! Thanks for the help and the great little plugin! Even though I'm using qutebrowser now, which has this built-in, I wouldn't be able to use Firefox now without this!
