### ISSUE TITLE
Filename template based on URL

### ISSUE THREAD

**Issue by wavexx** [jlebon/textern#5]
This is something that I miss from ItsAllText: when generating the temporary filename, it would be helpful set the basename of the file to some approximation of the URL where the textarea is located. For example:

`$TMPDIR/textern-[rnd]/github.com_jlebon_textern_issues-[rnd]`

Aside from the sanitization rules, this allows you to use autocommands in vim or filename patterns in emacs to set website-specific parameters. For example, I was using this on wikipedia to preset the filetype to wiki, on github to preset markdown, and so on.

**Comment by jlebon** [comment]
Hmm yeah, that makes sense. Thanks for the suggestion!

**Comment by jlebon** [comment]
This is fixed in the latest version of Textern (v0.4), though it is still under review. In the meantime, you can download the XPI directly [here](https://addons.mozilla.org/firefox/downloads/file/734874/textern-0.4-an+fx-linux.xpi).

Feel free to re-open if you encounter any issues! :)

**Comment by wavexx** [comment]
Thanks a lot. Works nicely!
