### ISSUE TITLE
better build diagnostics

### ISSUE THREAD

**Issue by archenemies** [jlebon/textern#54]
I've been trying to figure out why Textern isn't working, and came across the advice in your README that it should be cloned using submodules, or you have to run `git submodule update --init`.

Clearly I need to be better at reading instructions, but I also think this is the kind of thing that the build system should check for. If there is a missing directory, I would expect the install command to exit with an error.

Also it would be nice to have some better diagnostic procedure than "try configuring different key bindings, or use a different editor command". I want to know if the extension recognizes a certain textarea as being present; I want to know if my keybinding is being received by the extension; I want to know if the editor command is being executed, and the exit status. Maybe a "Enable debug output" checkbox? I think all of these should be pretty easy. That's basically what is being asked in #42.

See also #20. Also #48 "be an option when right-clicking in a textarea" would help somewhat, since then I could see that the add-on is actually there.

Thank you!

**Comment by archenemies** [comment]
Also, now that I have it working, I notice that the text box turns yellow when the keybinding is received and the editor is executed, this is a good diagnostic that could be mentioned in the README...

**Comment by jlebon** [comment]
Thanks for the feedback!

> Clearly I need to be better at reading instructions, but I also think this is the kind of thing that the build system should check for. If there is a missing directory, I would expect the install command to exit with an error.

This is fixed now.

> Also, now that I have it working, I notice that the text box turns yellow when the keybinding is received and the editor is executed, this is a good diagnostic that could be mentioned in the README...

Added a blurb to the README.

This leaves the better logging issue, which I entirely agree with. Let's close this ticket and track that in #42. Will whip something up for this.
