### ISSUE TITLE
Can't get it to work with vim

### ISSUE THREAD

**Issue by GOKOP** [jlebon/textern#59]
I have the editor configured as follows:
```
["termite", "-e", "vim", "+call cursor(%l,%c)"]
```
Vim is being opened, but it opens a new file which is empty and attempts at saving it just ask for a filename. I tried adding `"%s"` before the call cursor argument but it doesn't change anything.

With gvim configured like this:
```
["gvim", "+call cursor(%l,%c)"]
```
A file is opened (meaning that gvim says its path) but its contents aren't loaded and saving is impossible (can't open the file for edit)

A conventional editor like gedit works correctly

**Comment by migueldvb** [comment]
I had the same problem. It seems to be a termite issue. 

https://github.com/thestinger/termite/issues/308

Adding the filename argument together with the editor name between quotes works
fine.

```
["termite", "-e", "nvim %s"]
```

**Comment by GOKOP** [comment]
Thanks, it works! Writing this from vim :)
