### ISSUE TITLE
Double spaced lines in Slack

### ISSUE THREAD

**Issue by yjfguhd** [jlebon/textern#61]
This is probably an issue with Slack rather than Textern. I use Textern at the [Slack](https://app.slack.com/) message input area. Up pops GVim, I type in some multiline text. I save and quit. GVim disappears and my text appears in the Slack message input area. However, it appears with two newlines instead of one. Eg., I submit this:
```
line 1
line 2
line 3
```

It appears in Slack like this:
```
line 1

line 2

line 3

```
so I have to manually delete every other blank line.

I have verified that there is only one newline terminating each line in GVim. I even set the fileformat to dos (it's usually unix), to see if that would make a difference.

The only other GUI editors I have are kate and kwrite. I tried to test with those but when I saved the text in those editors, the text in the web browser didn't change. However, I'm not bothered about those. I did test it with pico (`["xterm", "-e", "pico"]`), and saw the same behaviour as with GVim.

Using Firefox 68.7.0esr, Python 3.7. Note I am not using the Slack "app", I am using the web site from a normal web browser.

**Comment by jlebon** [comment]
Thanks for the report! This is fixed in v0.7.
