### ISSUE TITLE
Leading whitespace is not copied

### ISSUE THREAD

**Issue by ilstam** [jlebon/textern#63]
Hello,

I have noticed that when using textern while composing an e-mail on gmail's web interface leading spaces of a line are not copied. I have tried other text fields in other websites and the spaces are copied just fine there. I tried with both gedit and gvim, but I guess this has nothing to do with the editor at all.

When I copy and paste text manually on the body of the e-mail the leading spaces are preserved. 

So any chance the plugin's behavior could be easily fixed?

Thanks.

**Comment by jlebon** [comment]
Thanks for the report. I can reproduce this as well. Will look into it.

**Comment by Matt-A-Bennett** [comment]
This is still the case for me using Gmail... is there way to fix it at all?

Thanks for this amazing extension!
