### ISSUE TITLE
Text fields cannot be updated

### ISSUE THREAD

**Issue by maxigaz** [jlebon/textern#7]
Using the latest git version of the native app and 0.4 of the addon with Firefox 55.0.3 under Manjaro Linux, even after I type something and save it inside the external editor, the text field remains unchanged inside the browser.

I have tried setting `kwrite` and `nvim-qt` as the external editor, and I get different behaviours:

- With kwrite, when I press Ctrl+Shift+E, the existing text (if there's any) is copied inside the editor, but saving does nothing.
- With neovim-qt, an empty file is opened and when I try to save, it gives me the error message "Can't open file for writing: no such file or directory".

**Comment by jlebon** [comment]
Hmm, odd. Are there any error messages that appear in the browser terminal? (Ctrl+Shift+J)

One thing to note is that you will want to make sure that the process started by the shortcut is valid for the duration of the edit. If it's like `gnome-terminal` for example, which just talks to the server that actually ends up opening the terminal window, the process exits immediately after, which makes Textern think that you are done editing (see also the last paragraph of the Usage section: https://github.com/jlebon/textern#usage).

**Comment by maxigaz** [comment]
I have `["kwrite"]` or `["nvim-qt"]` typed in the addon settings and neither of them are terminal applications. (I actually have tried using neovim through konsole, but that would only open konsole. I wonder if I replace `gnome-terminal` with `konsole` in line 21 in the gnome-terminal-wrapper script and have tmux installed, would it work with konsole, too?)

Also, I don't see anything in the browser terminal that might be related to Textern.

**Comment by jlebon** [comment]
> I wonder if I replace gnome-terminal with konsole in line 21 in the gnome-terminal-wrapper script and have tmux installed, would it work with konsole, too?)

It depends if the same issue is relevant to `konsole` as well, but it's worth a try.

If that doesn't work, maybe do a sanity test with something that definitely should work? E.g. something like: `["sh", "-c", "echo foobar > $0"]`. (It should basically immediately replace the textarea with "foobar"). If that works, at least we know the native app is functioning as it should.

**Comment by maxigaz** [comment]
After editing the wrapper file, I set `["/home/maxigaz/firefox-addon-helpers/gnome-terminal-wrapper.asc", "nvim"]`, but then on Ctrl+Shift+E I get a message that the process didn't exit successfully.

> ["sh", "-c", "echo foobar > $0"]. (It should basically immediately replace the textarea with "foobar").

That one works.

**Comment by jlebon** [comment]
So, a straightforward way of checking if you need to use the wrapper at all is by simply typing `konsole` in a terminal and checking if you get your prompt back or whether it blocks until the new terminal window is closed. Have you tried with `gvim` as well?

> but then on Ctrl+Shift+E I get a message that the process didn't exit successfully.

You can try removing the redirections to `DEVNULL` in `handle_message_new_text()` and check if any error messages from the editor show up in the browser console.

**Comment by maxigaz** [comment]
> So, a straightforward way of checking if you need to use the wrapper at all is by simply typing konsole in a terminal and checking if you get your prompt back or whether it blocks until the new terminal window is closed.

Indeed, I need to either close the new window of konsole or kill it from the original window with Ctrl+C.

> Have you tried with gvim as well?

Not yet.

> You can try removing the redirections to DEVNULL in handle_message_new_text()

I've found the line `async def handle_message_new_text(tmp_mgr, msg):
` in `textern.py`. Just below that, do I need to change

```python
        proc = await asyncio.create_subprocess_exec(
            *editor_args,
            stdout=asyncio.subprocess.DEVNULL,
            stderr=asyncio.subprocess.DEVNULL
        )
```
to the following?
```python
        proc = await asyncio.create_subprocess_exec(
            *editor_args
        )
```
PS: I've just tried that and I can't find any difference.

**Comment by jlebon** [comment]
> Indeed, I need to either close the new window of konsole or kill it from the original window with Ctrl+C.

Cool, so we've confirmed that the same issue as `gnome-terminal` is relevant here. So let's go back to:

> After editing the wrapper file, I set `["/home/maxigaz/firefox-addon-helpers/gnome-terminal-wrapper.asc", "nvim"]`, but then on Ctrl+Shift+E I get a message that the process didn't exit successfully.

Have you tried with other terminal-based editors? E.g. `vim` or `nano`? Can you paste the exact script you're using?

**Comment by maxigaz** [comment]
I've just tried it with nano. Same results.

Here's the [contents of the wrapper](https://bin.disroot.org/?456f510e904afc08#TQ5OrzeUwI/BuqSR7zciLYFBZhkhPGQCT/YvMrtg+IM=) and the [contents of textern.py](https://bin.disroot.org/?1be2a0607f5e8c57#Q4jGo6+BCrlMNgtJU4rYL/CADLPbA2goniGR3OYck6E=).

**Comment by jlebon** [comment]
> > Indeed, I need to either close the new window of konsole or kill it from the original window with Ctrl+C.

> Cool, so we've confirmed that the same issue as gnome-terminal is relevant here.

Sorry, I wasn't thinking clearly here. The fact that it *doesn't* return your prompt immediately means that you *don't* need the wrapper, which is great!

> Here's the contents of the wrapper

OK, so I think the issue here (besides the fact that you don't need the wrapper) is that according to the [konsole docs](https://docs.kde.org/trunk5/en/applications/konsole/command-line-options.html), the right switch to use is `-e`. So maybe just try something like this in your settings:

```
["konsole", "-e", "nano"]
```

**Comment by maxigaz** [comment]
> ```
> ["konsole", "-e", "nano"]
> ```
It works! (Both with nano and nvim.) Thank you for your help and patience!
