### ISSUE TITLE
Possibly change the default hotkey

### ISSUE THREAD

**Issue by joshpetit** [jlebon/textern#70]
This extension is such a blessing!! Literally, the exact thing that I need to make typing on most websites bearable haha.

At least for me, the shortcut `Ctrl + Shift + D` is taken by FireFox's bookmarking hotkey so I changed it to `Ctrl + Shift + F`. I'm not sure if this is the case for everyone though, but I'd maybe recommend changing the shortcut to something else as default if it is.

Thanks again for this extension!!

`This post was written in textern`

**Comment by jlebon** [comment]
Thanks for the kind feedback!

Yes, you're right re. the default shortcut being taken by Firefox nowadays. It actually used to be `Ctrl+Shift+E`, which also [caused conflicts](https://github.com/jlebon/textern/issues/30). I think we're destined to keep getting chased out of every default shortcut we select. :)

Anyway, `Ctrl+Shift+F` sounds reasonable to me. I'll take a look at changing it after testing.

**Comment by joshpetit** [comment]
Just noticed I forgot to close this, thanks for the update :)
