### ISSUE TITLE
Dead link on https://github.com/jlebon/textern

### ISSUE THREAD

**Issue by GrippenDynamik** [jlebon/textern#77]
This isn't a big deal, but on https://github.com/jlebon/textern there's a dead link:
"It is similar in functionality to the popular It's All Text! add-on"

It's All Text! => https://addons.mozilla.org/en-US/firefox/addon/its-all-text/ => Oops! We can’t find that page

**Comment by jlebon** [comment]
Fixed! Thanks for the report.
