### ISSUE TITLE
textern error when starting gvim/vim edit after CTRL-D

### ISSUE THREAD

**Issue by JontAlle** [jlebon/textern#79]
I upgraded my ubuntu from 20.04 to 22.04 and now textern fails.
THis was working great under 20.04.

It starts the edit but there is no VIM window presented.
My macro is
["gvim", "-f", "+call cursor(%l,%c)"]

If I try CTRL+D a second time it says that I already have the edit open. Rebooting clears this error, but not the problem.
What can I do to figure out what is going on, and why it is failing?

I'm going to try to clear the gvim macro and see if gedit comes up. 
Any other suggestions?

Jont Allen (jontallen@ieee.org)

**Comment by JontAlle** [comment]
I changed the macro for that of gedit, and the same problem. So it's not about the editor gvim I use. It's about starting the edit in its own window, as a separate process.

**Comment by JontAlle** [comment]
THis looks like it may be the error coming from python:

Apr 25 10:34:45 xear python3[5316]: Traceback (most recent call last):
Apr 25 10:34:45 xear python3[5316]:   File "/usr/lib/ubuntu-advantage/timer.py", line 144, in <module>
Apr 25 10:34:45 xear python3[5316]:     run_jobs(cfg=cfg, current_time=current_time)
Apr 25 10:34:45 xear python3[5316]:   File "/usr/lib/ubuntu-advantage/timer.py", line 120, in run_jobs
Apr 25 10:34:45 xear python3[5316]:     jobs_status[job.name] = {
Apr 25 10:34:45 xear python3[5316]: TypeError: 'str' object does not support item assignment
Apr 25 10:34:45 xear systemd[1]: ua-timer.service: Main process exited, code=exited, status=1/FAILURE
Apr 25 10:34:45 xear systemd[1]: ua-timer.service: Failed with result 'exit-code'.
Apr 25 10:34:45 xear systemd[1]: Failed to start Ubuntu Advantage Timer for running repeated jobs.
Apr 25 10:34:58 xear kernel: [ 1431.651571] [UFW BLOCK] IN=enx00e04c6805c2 OUT= MAC=00:e0:4c:68:05:c2:dc:a6:32:d0:16:39:08:00 SRC=192.17.220.197 DST=192.17.223.134 LEN=227 TOS=0x00 PREC=0x00 TTL=64 ID=33698 DF PROTO=UDP SPT=1900 DPT=48212 LEN=207

**Comment by jlebon** [comment]
Hello,

Were you able to fix it then? Check out also [the troubleshooting section in the README](https://github.com/jlebon/textern#troubleshooting).
