### ISSUE TITLE
Need a backup option

### ISSUE THREAD

**Issue by nickurbanik** [jlebon/textern#83]
I have lost a few extensive editing sessions through losing the connection between Firefox and textern, either because I accidentally closed the editing page in Firefox or some other user error over a long editing session.

I just lost two hours of very good work.  That is the final straw.

I am now going to implement a backup system on my machine here, and will attach a patch implementing that to this bug report after it is done.

**Comment by nickurbanik** [comment]
[textern-backup.patch.gz](https://github.com/jlebon/textern/files/9730405/textern-backup.patch.gz)
This patch implements backups to ~/.textern.  Please add this to the code base so that other people do not suffer the frustration of losing hours of precious work.

**Comment by jlebon** [comment]
I'm sorry that happened to you. I'm open to having an opt-in option for this. See also discussions in https://github.com/jlebon/textern/issues/6.

Can you open a PR with your patch so I can review it more easily?
