### ISSUE TITLE
New tag / Update Firefox Add-On

### ISSUE THREAD

**Issue by MaxGyver83** [jlebon/textern#89]
`about:addons` says the last update was May 13, 2022. The latest tag at GitHub was in 2020. There were new commits since then.

Could you update the version available in Firefox, please? And create a new tag (if this has any meaning)?

**Comment by jlebon** [comment]
I'm planning to get https://github.com/jlebon/textern/pull/88 in and cut a release soon.

**Comment by jlebon** [comment]
v0.8 has been cut and pushed to AMO.
